from decouple import config

ROOT_FILE = "index.html"

REDIS_PORT = config("REDIS_PORT")
REDIS_URL = config("REDIS_URL")
REDIS_HOST = config("REDIS_HOST")
REDIS_PASSWORD = config("REDIS_PASSWORD")
SITE_EMAIL = config("SITE_EMAIL")
SITE_EMAIL_PASS = config("SITE_EMAIL_PASS")
SITE_KEY = config("SITE_KEY")
IMAGEKIT_ID = config("IMAGEKIT_ID")
IMAGEKIT_PUBLIC_KEY = config("IMAGEKIT_PUBLIC_KEY")
IMAGEKIT_PRIVATE_KEY = config("IMAGEKIT_PRIVATE_KEY")
IMAGEKIT_URL_ENDPOINT = config("IMAGEKIT_URL_ENDPOINT")
LIVECHAT_API_URL = config("LIVECHAT_API_URL")


