SUCCESSFUL_MSG = "sucessful";
NOT_FOUND_MSG = "not found";
FORBIDDEN_MSG = "request forbidden";
CRASH_MSG = "unexpected issue";
BAD_REQUEST_MSG = "invalid request";
SUCCESSFUL = 200;
NOT_FOUND = 404;
FORBIDDEN = 403;
CRASH = 503;
BAD_REQUEST = 400
