# Generated by Django 3.2.23 on 2023-11-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('temporary_id', models.CharField(max_length=30, unique=True)),
                ('profile_image', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=200)),
                ('deleted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('temporary_id', models.CharField(max_length=30, unique=True)),
                ('profile_image', models.CharField(blank=True, max_length=100, null=True)),
                ('wachlist', models.BooleanField(blank=True, null=True)),
                ('likeslist', models.BooleanField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, unique=True)),
            ],
        ),
    ]
