# Generated by Django 5.0 on 2024-01-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
