# Generated by Django 5.0 on 2024-01-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_admin_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='temporary_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='temporary_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
