# Generated by Django 5.0 on 2024-01-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_admin_temporary_id_alter_user_temporary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='temporary_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='temporary_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
