# Generated by Django 5.0 on 2024-01-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_admin_temporary_id_alter_user_temporary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
