# Generated by Django 5.0.1 on 2024-01-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_admin_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
