# Generated by Django 5.0.1 on 2024-02-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_user_likeslist_remove_user_wachlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
