# Generated by Django 5.0.1 on 2024-02-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_watchlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlists',
            name='email',
            field=models.CharField(max_length=80),
        ),
    ]
