# Generated by Django 5.0.1 on 2024-02-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_watchlists_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlists',
            name='user',
            field=models.IntegerField(),
        ),
    ]
