# Generated by Django 5.0.1 on 2024-02-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlists',
            name='id',
        ),
        migrations.AlterField(
            model_name='watchlists',
            name='slug',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
