# Generated by Django 5.0.1 on 2024-02-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_watchlists_id_alter_watchlists_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('creator_email', models.CharField(max_length=80)),
                ('creator_id', models.CharField(max_length=80)),
                ('creator_username', models.CharField(max_length=80)),
                ('anime_title', models.CharField(max_length=200)),
                ('unlimited', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=True)),
                ('limit', models.IntegerField()),
            ],
        ),
    ]
